### ISSUE TITLE
Add check option - validation

### ISSUE THREAD

**Issue by MadLittleMods** [bhargavrpatel/gulp-prettier#12]
Add check option to use in a validation/linting step instead of rewriting

[`prettier.check(source [, options])`](https://prettier.io/docs/en/api.html#prettierchecksource-options)

**Comment by TheDancingCode** [comment]
So you'd like an option to check if a file needs formatting, but not actually format it?
Could you expand a bit upon your use case?

**Comment by TheDancingCode** [comment]
All right. Let’s figure out how to best implement this functionality.

I would go for a separate function that throws an error when it encounters a file that needs formatting. For the error to be useful and informative the plugin should throw it only after having checked all the files, and the error message should contain the names of all the offending files.

Would you agree?

**Comment by MadLittleMods** [comment]
@TheDancingCode Thanks for #13 and the v2.1.0 release! 🚀
