### ISSUE TITLE
Does it support the "--write" command?

### ISSUE THREAD

**Issue by PeteDuncanson** [bhargavrpatel/gulp-prettier#14]
Trying to get this added to our build chain and I'd like it to pretty the files in place (ideally only if needed). Checking the docs I can see there is the write command which I'd normally use if running it manually but seems to be no way to wire this into the gulp task. https://prettier.io/docs/en/cli.html#write

Doable?

**Comment by TheDancingCode** [comment]
To format the files in places you just write them back to the folder they were in. To only overwrite a file when the content has changed, add a conditional step with `gulp-if`.

```js
const gulp = require('gulp');
const prettier = require('gulp-prettier');
const gulpif = require('gulp-if');

gulp.task('format', function() {
  return gulp.src('src/*.js')
    .pipe(prettier())
    .pipe(gulpif(file => file.isPrettier, gulp.dest('src')));
});
```

**Comment by PeteDuncanson** [comment]
Of course! Works a treat. Thank you :)
