### ISSUE TITLE
Change error message to something more appropriate

### ISSUE THREAD

**Issue by kaelig** [bhargavrpatel/gulp-prettier#9]
Thank you for this project, however… could you please remove this F-bomb from the error message?

https://github.com/bhargavrpatel/gulp-prettier/blob/7d790fd1a41f24c084c4e43baa2460d2fe2295e3/index.js#L48

**Comment by bhargavrpatel** [comment]
@kaelig Yes good idea. Would you mind making a pull request with a more appropriate commit message?

**Comment by Chmylov** [comment]
I just installed gulp-prettier but i am still getting 'there was a fucking error b!!'. Package.json says "gulp-prettier": "^1.1.0", is installed. It seems that npm is pulling old code.

**Comment by bhargavrpatel** [comment]
@TheDancingCode Assuming it is: https://www.npmjs.com/~thedancingcode I've added you as a collaborator.

**Comment by TheDancingCode** [comment]
The right username indeed. Now published in v2.0.0!

**Comment by Chmylov** [comment]
Thank you for your quick response! I just tested it and it works great! Thanks for making it and keep up the good work!

**Comment by kaelig** [comment]
Thank you!
